###
POST http://localhost:3001/Registro
content-type: application/json

{
    "username": "jesus",
    "password":"34126011229",
    "email":"obregoso06@gmail.com"
}

###

POST http://localhost:3001/Registro/Verificacion
content-type: application/json

{
    "codigo":"960411"
}

###
POST http://localhost:3001/Login
content-type: application/json

{
    "email": "obregoso06@gmail.com",
    "password":"34126011229"
}

###
GET  http://localhost:3001/inicio

###

GET  http://localhost:3001/Desconexion

###
GET  http://localhost:3001/servicio

###
POST http://localhost:3001/servicio
content-type: application/json

{
    "servicio":"logistica",
    "precio":"130",
    "stock":3,
    "descripcion":"logistica",
    "imagen":"https://plus.unsplash.com/premium_photo-1663091967607-2e15b89f4d6e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fG9maWNpb3N8ZW58MHx8MHx8fDA%3D"
    
}
